import type { Asset } from './types';

export const mockAssets: Asset[] = [
  {
    id: '1',
    name: 'Portátil del Director de TI',
    productType: 'Laptop',
    model: 'MacBook Pro 14"',
    serialNumber: 'SN-MBP14-001',
    purchaseDate: new Date('2022-01-15T00:00:00Z'),
    status: 'Activo',
  },
  {
    id: '2',
    name: 'Monitor de Sala de Conferencias',
    productType: 'Monitor',
    model: 'Dell U2721DE',
    serialNumber: 'SN-DELL27-002',
    purchaseDate: new Date('2021-03-20T00:00:00Z'),
    status: 'Activo',
  },
  {
    id: '3',
    name: 'Teclado de repuesto 1',
    productType: 'Keyboard',
    model: 'Logitech MX Keys',
    serialNumber: 'SN-LOGI-K-003',
    purchaseDate: new Date('2023-05-10T00:00:00Z'),
    status: 'Activo',
  },
  {
    id: '4',
    name: 'Viejo Portátil de Ventas',
    productType: 'Laptop',
    model: 'ThinkPad T480s',
    serialNumber: 'SN-TP480-004',
    purchaseDate: new Date('2018-06-01T00:00:00Z'),
    status: 'Activo',
  },
  {
    id: '5',
    name: 'PC de Recepción',
    productType: 'Desktop',
    model: 'HP EliteDesk 800',
    serialNumber: 'SN-HPED-005',
    purchaseDate: new Date('2019-11-25T00:00:00Z'),
    status: 'Obsoleto',
  },
    {
    id: '6',
    name: 'Ratón ergonómico',
    productType: 'Mouse',
    model: 'Logitech MX Master 3',
    serialNumber: 'SN-LOGI-M-006',
    purchaseDate: new Date('2020-08-12T00:00:00Z'),
    status: 'Activo',
  },
  {
    id: '7',
    name: 'Monitor Secundario de Diseño',
    productType: 'Monitor',
    model: 'LG 27UL850-W',
    serialNumber: 'SN-LG27-007',
    purchaseDate: new Date('2019-02-28T00:00:00Z'),
    status: 'De baja',
  },
];
